SELECT*FROM cтраны ORDER BY Площадь DESC LIMIT 5;
SELECT*FROM cтраны WHERE Континент = 'Африка' AND Население < 1000000;
SELECT*FROM cтраны WHERE Континент != 'Европа' AND Население > 5000000 AND Площадь < 100000;
SELECT*FROM cтраны WHERE ((Континент = 'Северная Америка' OR Континент = 'Южная Америка') AND Население > 20000000) OR (Континент = 'Африка' AND Население > 30000000);
SELECT*FROM cтраны WHERE (Население BETWEEN 10000000 AND 100000000) AND Площадь < 500000;
SELECT*FROM cтраны WHERE Название NOT LIKE 'К%';
SELECT*FROM cтраны WHERE Название LIKE '__а%и_';
SELECT*FROM cтраны WHERE Название LIKE '_а%' OR Название LIKE '_е%' OR Название LIKE '_ё%' OR Название LIKE '_и%' OR Название LIKE '_й%' OR Название LIKE '_о%' OR Название LIKE '_у%' OR Название LIKE '_ы%' OR Название LIKE '_э%' OR Название LIKE '_ю%' OR Название LIKE '_я%';
SELECT*FROM cтраны WHERE Название LIKE 'К%' OR Название LIKE 'Л%' OR Название LIKE 'М%' OR Название LIKE 'Н%' OR Название LIKE 'О%' OR Название LIKE 'П%';
SELECT*FROM cтраны WHERE Название LIKE 'А%' OR Название LIKE 'В%' OR Название LIKE 'Г%';
SELECT*FROM cтраны WHERE Столица IS NOT NULL;
SELECT*FROM cтраны WHERE Континент = 'Африка' OR Континент = 'Южная Америка' OR Континент = 'Северная Америка';